version: "3.9"
services:
  app:
    image: alpine:latest
    stdin_open: true 
    tty: true     
    networks:
      - network2

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgreostgresql/data
    networks:s
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/p
      - network1
    volumes:
      - C:\Users\Lady dayan cabrera\tarea/volumes/datos-pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  
 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mando@mandalore.sw
      PGADMIN_DEFAULT_PASSWORD: grogu
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "80:80"
    networks:
      - network2
      - network1
    volumes:
      - C:\Users\Lady dayan cabrera\tarea/volumes/pgadmin4:/var/lib/pgadmin

networks:
  network1:
  network2: